export const popupProfile = document.querySelector('#popupProf'); // попап для изменения профиля
export const popupPlace = document.querySelector('#popupPlace'); // попап для добавления нового поста
export const formProfile = popupProfile.querySelector('#formProf'); // попап для просмотра постов 
export const formPlace = popupPlace.querySelector('#formPlace'); // попап для просмотра постов 
export const profileChange = document.querySelector('.profile__change'); // кнопка для изменения профиля
export const placeAdd = document.querySelector('.profile__add'); // кнопка для добавления поста
export const profileName = document.querySelector('.profile__name'); // Имя в профиля
export const profilAbout = document.querySelector('.profile__about'); // Род деятельности в профиле
export const nameInput = formProfile.querySelector('#form__name'); // Инпут для имени
export const aboutInput = formProfile.querySelector('#form__about'); // Инпут для деятельности
export const placeName = formPlace.querySelector('#form__place'); // Инпут для названия нового поста
export const placeLink = formPlace.querySelector('#form__link'); // Инпут для ссылки на новый пост